version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: output.log
    maxBytes: 1024000
    backupCount: 5
loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console, file]
root:
  level: DEBUG
  handlers: [console, file]